--Testbench generated by Alexandre P testbench generator ;))
library IEEE;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity engine_tb is
end engine_tb;

architecture simulate of engine_tb is

component engine
Port(
		CLK : in std_logic;
		RST : in std_logic
	);
end component;

--Internal signals
signal s_CLK : std_logic;
signal s_RST : std_logic;


constant CLK_period : time := 20.0 ns;

begin

uut :engine
	Port map(
		CLK => s_CLK,
		RST => s_RST
	);

--Stimulus process
stimulus : process
	begin
		wait for 40.0 ns;
		s_CLK <= '0';
		s_RST <= '0';
		wait for 40.0 ns;
		s_RST <= '1';
		--Code here
		wait;
	end process;

--Clock process definiton
CLK_process : process
	begin
		s_CLK <= '0';
		wait for CLK_period/2;
		s_CLK <= '1';
		wait for CLK_period/2;
	end process;

end;
